### ISSUE TITLE
Different edge counts in graph and edges field due to zero-distance nodes

### ISSUE THREAD

**Issue by kramsretlow** [pszufe/OpenStreetMapX.jl#32]
Hi and thanks for your work on this package. I've been getting acquainted with it the last 2 days.

Let's say my `MapData` is stored in an object named `md` .  For my data set (map of Shanghai, over 170k edges), I found that `length(md.e) - ne(md.g)` equals 6  (rather than the zero that I expected).

After looking at the offending edges I found that each edge consists of a pair of nodes with `distance(node1, node2) == 0`.  I see that in `parseMap.jl` the graph is created via `g = LightGraphs.DiGraph(w)`, where `w` contains weights obtained by a call to `distance( )`.  So the edges don't get created by LightGraphs.

At least this is my understanding of what's happening.  It seems like a rare thing to have zero-distance edges in the OSM data, so I thought I would bring this to your attention.  I don't know if it is design intent to maintain a 1:1 correspondence between `edges(md.g)` and `md.e`, but this occurrence breaks the correspondence.

Thanks!

**Comment by pszufe** [comment]
@kramsretlow is all OK now? May I close the issue?

**Comment by kramsretlow** [comment]
Sorry, I was away from this for a long weekend.

It works now, thank you.  The two ways of getting the edges correspond for my data set. 

I had a little trouble getting updated to the new version--I guess some compatibility/dependencies need to be updated?
* In my default environment 0.2.0 was blocked by other packages that required JSON to be at v0.21.0.  
* In a new, empty environment, adding OpenStreetMapX worked but then blocked me from adding OpenStreetMapXPlot (!). 
* Adding OpenStreetMapXPlot first to an empty environment prevented v0.2.0 from being added (it fell back to v0.1.13).

I still have a question about the weights but maybe that's a different issue 😄

**Comment by pszufe** [comment]
Thanks for checking, I bumped the version to `v0.2.1` - should now be OK :-)

**Comment by kramsretlow** [comment]
JSON compatibility seems fine, but still having a hard time getting OpenStreetMapX and OpenStreetMapXPlot to coexist.  I just created a  tiny pull request in OpenStreetMapXPlot.jl to bump OpenStreetMapX's version in [compat].

Cheers 🍺

**Comment by pszufe** [comment]
Hi,
does it work for you now with the new versions released week ago? Can I close the issue?

**Comment by kramsretlow** [comment]
Yes it works 🍺
