### ISSUE TITLE
MethodError in reading a .osm file

### ISSUE THREAD

**Issue by kavir1698** [pszufe/OpenStreetMapX.jl#40]
I have downloaded a city osm from [here](https://download.openstreetmap.fr/extracts/) and I tried reading it.

This gives me an empty `MapData`:
```julia
julia> zurich = get_map_data(map_path, only_intersections=true,use_cache=false)

MapData(OpenStreetMapX.Bounds{LLA}(0.0, 0.0, 0.0, 0.0), Dict{Int64,ENU}(), OpenStreetMapX.Way[], Dict{Int64,Set{Int64}}(), {0, 0} directed simple Int64 graph, Dict{Int64,Int64}(), Int64[], Tuple{Int64,Int64}[], 0×0 SparseArrays.SparseMatrixCSC{Float64,Int64} with 0 stored entries, Int64[])
```

And this gives me an error:
```julia
zurich = get_map_data(map_path, only_intersections=false,use_cache=false)

ERROR: MethodError: no method matching get_edges(::Dict{Any,Any}, ::Array{OpenStreetMapX.Way,1})
Closest candidates are:
  get_edges(::Dict{Int64,T}, ::Array{OpenStreetMapX.Way,1}) where T<:Union{ECEF, ENU} at C:\Users\Ali\.julia\packages\OpenStreetMapX\pfbvr\src\routing.jl:5
Stacktrace:
 [1] MapData(::OpenStreetMapX.OSMData, ::Set{Int64}, ::Bool; trim_to_connected_graph::Bool, remove_nodes::Set{Int64}) at C:\Users\Ali\.julia\packages\OpenStreetMapX\pfbvr\src\parseMap.jl:162
 [2] get_map_data(::String, ::Nothing; road_levels::Set{Int64}, use_cache::Bool, only_intersections::Bool, trim_to_connected_graph::Bool) at C:\Users\Ali\.julia\packages\OpenStreetMapX\pfbvr\src\parseMap.jl:102
 [3] top-level scope at REPL[76]:
```
---
I am using OpenStreetMapX v0.2.3 and Julia 1.5.2

**Comment by pszufe** [comment]
What file have you downloaded?
Note that you need XML *.osm file and on this web page I only see files in the binary *.pbf format.

**Comment by kavir1698** [comment]
I downloaded a `.pbf` file and the converted it to `.osm` using the `osmconvert` tool (provided by OpenStreeMap org).

**Comment by pszufe** [comment]
OpenStreetMapX relies on map bounds being defined in the file. 
Somehow in your files those bounds are missing. Try adding them manually.
```
osmconvert64 zurich.osm.pbf --drop-author --drop-version -b=8.40,47.25,8.70,47.50 -o=zurichF.osm
```
Note that I did not manage to replicate your error - I was just observing an empty `MapData` object.

Let me know if this works for you.

**Comment by kavir1698** [comment]
Thanks for your help. Adding the bounds solved the issue in both cases. I just don't see where you found those exact numbers.

**Comment by pszufe** [comment]
> I just don't see where you found those exact numbers for bounds

I guessed. These are just any numbers that seemed to be more or less OK - you need to pick up more exact numbers.
