### ISSUE TITLE
Displaying Buildings

### ISSUE THREAD

**Issue by GGomez11** [pszufe/OpenStreetMapX.jl#45]
Hello,

I've recently been playing with this package and was wondering it it's possible to parse the nodes that are buildings in a .osm file? My goal is to plot buildings but I'm not sure if this is possible.

Thanks for all your work. 

Best Regards,
Greg

**Comment by pszufe** [comment]
Hi,
we only parse routes (see https://github.com/pszufe/OpenStreetMapX.jl/blob/master/src/parseMap.jl)
I believe LightOSM.jl claims that they parse buildings. 
Przemek.
