### ISSUE TITLE
How do I get data?

### ISSUE THREAD

**Issue by mkborregaard** [pszufe/OpenStreetMapX.jl#5]
Sorry for the stupid Q, but I can't see how to download data from OSM's servers?
Thanks!

**Comment by bkamins** [comment]
@bartoszpankratz - can you help?

**Comment by pszufe** [comment]
@mkborregaard thank you for using OpenStreetMapX. 
I updated the README page - let me know if this is what you needed.

**Comment by mkborregaard** [comment]
Yes, thank you!
